### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by VladimirFokow** [lukasgeiter/mkdocs-awesome-pages-plugin#100]
if you have something like this (`index.md` is not the first in the order)

```yml
nav:
  - idx: 
    - home/other.md
    - home/index.md
    - ... | about/**
    - ... | flat | home/**
```

then the `...` is broken: both are rendered as only one `AWESOME_PAGES_REST`

TODO: should I create a reproducible example or is this an expected behavior?
