### ISSUE TITLE
Sub-subdirectories not supported?

### ISSUE THREAD

**Issue by eXpl0it3r** [lukasgeiter/mkdocs-awesome-pages-plugin#104]
Am I understanding this correctly, that sub-subdirectories are not supported?

For example I'd have the structure:
```
└───tutorials
    └───2.6
        ├───getting-started
        └───system
```

How would I address the `2.6` directory?

If I write something like the following, mkdocs just crashes:

```yaml
nav:
    - Home: index.md
    - Learn:
        - tutorials/2.6
```

```
mkdocs_awesome_pages_plugin.navigation.NavEntryNotFound: Nav entry "tutorials/2.6" not found. [.pages]
```

Using just a subdirectory works:

```yaml
nav:
    - Home: index.md
    - Learn:
        - tutorials
```
