### ISSUE TITLE
Link to files outside of folder

### ISSUE THREAD

**Issue by NFanoe** [lukasgeiter/mkdocs-awesome-pages-plugin#108]
Is it possible to link to a file in a relative path? Like

``` yaml
title: About this amazing topic
nav:
  - Amazing topic: ../../amazing_topic.md
  - ... | *.md
```

Or even 
`- Danish Broadcasting Service: https://dr.dk`

There won't be a page for that last one, of course, but it would just open the URL.

?
I've tried, of course, and failed. Thought maybe there's a special syntax I'm not aware of ..?
