### ISSUE TITLE
Cannot create web redirects with navigation items

### ISSUE THREAD

**Issue by rieger-jared** [lukasgeiter/mkdocs-awesome-pages-plugin#12]
In vanilla mkdocs, you're able to define your mkdocs.ymal to have web pages that purely redirect to a link. 

```yaml
nav:
  - Home: 'index.md'
  - Stack Overflow: 'https://stackoverflow.com/'
```

This would create navigation that showed an item called Stack Overflow and allow it to be clickable. Therefore a page was not needed. Is there a way to configure this already with awesome-pages or would it need to be implemented?
