### ISSUE TITLE
[Question] Make menu header a page

### ISSUE THREAD

**Issue by Stanzilla** [lukasgeiter/mkdocs-awesome-pages-plugin#13]
Hey there, I'm currently looking for a way to have clicking a menu header open to a page in addition to expanding the submenu. Any idea how to best do that?

Example:

```yaml
-index.md
-category: category.md
  - sub-page: sub-page.md
  - sub-page2: sub-page2.md
- category2: category2.md
  - sub-page: sub-page.md
  - sub-page2: sub-page2.md
```
