### ISSUE TITLE
migrating from awesome-pages: the .nav.yml is not loaded if using same dir root instead of docs folder

### ISSUE THREAD

**Issue by anb0s** [lukasgeiter/mkdocs-awesome-pages-plugin#130]
I'm migrating from awesome-pages and have replaced to this plugin and now miss something to have the new `.nav.yml` loaded from the root directory, because using [same-dir](https://github.com/oprypin/mkdocs-same-dir) plugin and `docs_dir: "."` instead of `docs/`.

How to configure it? I've placed the file `.nav.yml` to the root and also to a subfolder `docs/` but it looks like `nav:` is not loaded

```yml
# replaced navigation with plugin: https://lukasgeiter.github.io/mkdocs-awesome-nav/migration-v3/#nav_1

# https://lukasgeiter.github.io/mkdocs-awesome-nav/features/flattening/
flatten_single_child_sections: true
nav:
- Overview: 'README.md'
- 'Content-Demo':
  - "docs/**/*"
- 'Doxygen-Demo':
  - 'Links': 'doxygen-demo/links.md'
  - 'Classes':
    - 'Class List': 'doxygen-demo/annotated.md'
    - 'Class Index': 'doxygen-demo/classes.md'
    - 'Class Hierarchy': 'doxygen-demo/hierarchy.md'
    - 'Class Members': 'doxygen-demo/class_members.md'
    - 'Class Member Functions': 'doxygen-demo/class_member_functions.md'
    - 'Class Member Variables': 'doxygen-demo/class_member_variables.md'
    - 'Class Member Typedefs': 'doxygen-demo/class_member_typedefs.md'
    - 'Class Member Enumerations': 'doxygen-demo/class_member_enums.md'
  - "Namespaces":
    - "Namespace List": "doxygen-demo/namespaces.md"
    - "Namespace Members": "doxygen-demo/namespace_members.md"
    - "Namespace Member Functions": "doxygen-demo/namespace_member_functions.md"
    - "Namespace Member Variables": "doxygen-demo/namespace_member_variables.md"
    - "Namespace Member Typedefs": "doxygen-demo/namespace_member_typedefs.md"
    - "Namespace Member Enumerations": "doxygen-demo/namespace_member_enums.md"
  - "Functions": "doxygen-demo/functions.md"
  - "Variables": "doxygen-demo/variables.md"
  - "Macros": "doxygen-demo/macros.md"
  - "Files": "doxygen-demo/files.md"
  - "Pages": "doxygen-demo/pages.md"
  - "modules": "doxygen-demo/modules.md"
- 'Changelog': 'CHANGELOG.md'
- 'Contributing': 'CONTRIBUTING.md'
- 'License':
  - 'CHECKLIST.md'
  - 'LICENSE.md'
  - 'COPYING.md'
- 'Tags': 'tags.md'
```

folder structure:

```
docs
  |_badges.md
  |_caption.md
  |_cards.md
  |_diagrams.md
  |_...
doxygen-demo
  |_links.md
  |_ ...
CHANGELOG.md
CHECKLIST.md
CONTRIBUTING.md
COPYING.md
README.md
tags.md
mkdocs.yml
.nav.yml
```

**Comment by anb0s** [comment]
also tried to configure it, but no effect:

```yml
  awesome-nav:
    filename: ".nav.yml"
```

how to debug if the file is loaded at all?

**Comment by mohamedmoanes** [comment]
I am Facing the same issue

**Comment by lukasgeiter** [comment]
Thanks for reporting this compatibility issue with `same-dir`.

Since v3, this plugin relies on the files collection that mkdocs provides, instead of reading `.nav.yml` from the filesystem directly. This has many advantages when it comes to compatibility with other plugins, but unfortunately makes it incompatible with the current version of `same-dir`. `same-dir` excludes unknown files that are located directly under the root directory from further processing. It is mentioned in the [README](https://github.com/oprypin/mkdocs-same-dir/blob/master/README.md) and [here is the relevant section in the code](https://github.com/oprypin/mkdocs-same-dir/blob/9218f4a22ee231599e7c697525ab2ec37893a256/mkdocs_same_dir/plugin.py#L26-L33).

I don't think there's a clean fix that I could make for this in `awesome-nav`. I would have to store a copy of the files collection, before `same-dir` removes the `.nav.yml` file.

@oprypin Do you see a good solution for this incompatibility? Adding an exception for `.nav.yml` to `same-dir` is the first thing that comes to my mind, although that wouldn't cover every case because the filename is customizable.

**Comment by nihalshah-dev** [comment]
from the discussions above fyi !! my thoughts - 

Right now the plugin assumes `.nav.yml` files are located only in a `docs/` directory,  I think there might be a way out that the plugin respects the `docs_dir` setting and search for `.nav.yml` file relative to configured directory as well - 

Something like this could work ig -

**mkdocs.yml -**
```yaml
plugins:
  - same-dir
  - awesome-nav:
      nav_file: ".nav.yml"        # custom nav filename
      respect_docs_dir: true      # respect docs_dir setting
      fallback_to_root: true      # fallback search in root
```

plugin.py - 
```py
class AwesomeNavConfig(config_options.Config):
    nav_file = config_options.Type(str, default='.nav.yml')
    search_paths = config_options.Type(list, default=None)
    respect_docs_dir = config_options.Type(bool, default=True)
```
