### ISSUE TITLE
Allow sections to be configured in `nav`

### ISSUE THREAD

**Issue by athal7** [lukasgeiter/mkdocs-awesome-pages-plugin#30]
In order to achieve top-level sections (e.g. to utilize [material navigation tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs)), I need to either:
- use this plugin but restructure all of my docs based on those sections
- use the native mkdocs nav functionality, and miss out on the good features here including the spread operator for the "rest" of the pages

It would be great to be able to specify custom sections in the `.pages` file of the `docs_dir`, e.g.:

```yaml
nav:
  - Vision:
    - principles.md
    - roadmap.md
  - People:
    - team.md
    - advisors.md
  - ...
```
