### ISSUE TITLE
[FR] Extend "flat" to also work with dirs

### ISSUE THREAD

**Issue by jaklan** [lukasgeiter/mkdocs-awesome-pages-plugin#53]
The new `flat` feature is great, but unfortunately it has some limitations:

1. The following one works as expected - under `Project Name` I get one, flat list of pages from `docs/` and from all subdirs inside `docs/`.
```yaml
nav:
  - Projects:
     - Project Name:
        - ... | flat | projects/project-name/docs/**/*
```
However - what If I **don't** want to flat subdirs? What I mean is - I would like to avoid `Docs` in nav, but I would like to preserve all the subdirs, so I get:
- Projects/
  - Project Name/
     - Page 1
     - Page 2
     - Subdir/
        - Page 3

And of course the point is not to define all the subdirs manually, but to autogenerate it. 

I tested 2 approaches:
- in the below scenario we only get `Page 1` and `Page 2`; `Subdir` and `Page 3` are not included at all.
```yaml
nav:
  - Projects:
     - Project Name:
        - ... | flat | projects/project-name/docs/*
```
- I tested both above variants with additional `.pages` file inside `projects/project-name/docs/` with various combinations, i.a. with `subdir` specified explicitly:
```yaml
nav:
  - subdir
  - ...
```
but it didn't have any impact on results - they were exactly the same as before.

2. Another issue I have is the usage of that new functionality within `.pages` files. I wanted to use such nav in main `mkdocs.yml`:
```yaml
nav:
  - ... | projects/**/*
```
to automatically populate all the projects. It works great as it is, but of course then we have unwanted `Docs` in nav. My idea was to define `.pages` file in each project and specify there to flat the sub-structure to avoid `Docs` in nav. 

I created such `projects/project-name/.pages` file then:
```yaml
nav:
  - ... | flat | docs
```
but it doesn't work - I get exactly the same results as without the file, so `Docs` stays in nav. I did a few more tests:
- `- ... | flat` - the same result
- `- ... | flat | docs/*` - doesn't work at all, nothing is generated
- `- docs | flat` - returns an error: `mkdocs_awesome_pages_plugin.navigation.NavEntryNotFound: Nav entry "docs | flat" not found.`

As mentioned by @lukasgeiter in #36:
> The feature was not designed to do anything more than flatten the list of remaining pages.

and that's the reason why it doesn't cover more complicated scenarios, when we actually need to work more with dirs than just pages. That FR is about extending the functionality of `flat`.

**Comment by jaklan** [comment]
Just one more comment for the full context - to achieve the result mentioned in point 1) with current capabilities, we need to do this:
```yaml
nav:
  - Home: README.md
  - Projects:
    - Project Name:
      - ... | flat | projects/project-name/docs/*.md
      - Subdir:
        - ... | flat | projects/business-effectiveness/docs/subdir/*.md
      - Subdir2:
        - ... | flat | projects/business-effectiveness/docs/subdir2/*.md
        - Subsubdir:
          - ... | flat | projects/business-effectiveness/docs/subdir2/subsubdir/*.md
```
All above just to avoid `Docs` in nav. As you can see - it's almost impossible to maintain.
