### ISSUE TITLE
awesome-pages and i18n compatibility using .pages

### ISSUE THREAD

**Issue by Argald0** [lukasgeiter/mkdocs-awesome-pages-plugin#58]
Hi there !

I have just read the issues on @ultrabug i18n compatibility with awesome-pages from the end of 2021, and from what I read I understood that everything works fine unless there is something unexpected in the `mkdocs.yml` such as `...`. Knowing this issue, I decided to go for a `.pages` file, but I do get 404 errors. 

I wasn't sure whether I should put it here or as ultrabug's plugin issue, but I believe I'm doing something wrong with the `.pages` file, that's why I'm posting here. Would you mind giving it a look plz ?

First of all, I have this project : 
![image](https://user-images.githubusercontent.com/78689575/149599674-c355375f-96b4-4b4a-be87-634449767b7b.png)

```
mkdocs.yml
docs/
├─ .pages 
├─ index.md
├─ index.fr.md
├─ file2.md
└─ file2.fr.md
```

With this `mkdocs.yml` :
```yml
site_name: My Docs
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  palette:
    scheme: slate
    primary: blue grey
    accent: amber
extra:
  alternate:
    - name: English
      link: ./
      lang: en
    - name: Français
      link: ./fr/
      lang: fr
plugins:
    - search
    - awesome-pages
    - i18n:
        default_language: en
        languages:
          en: english
          fr: français
        nav_translations:
          fr:
            'Welcome': 'Bienvenue'
            'File 2 awesome pages': 'Fichier 2 awesome pages'
```

This is what my `.pages` file looks like : 
```yml
nav:
    - Welcome: index.md
    - File 2 awesome pages: file2.md
 ```

While browsing the `mkdocs serve`, if I change the language from default (english) to french, and try to access one of the pages it outputs a 404 error : 
![image](https://user-images.githubusercontent.com/78689575/149600842-b9c477b4-bc2c-4155-9c0a-ad088597387a.png)

Whereas if I stay in the default language it doesn't : 
![image](https://user-images.githubusercontent.com/78689575/149600802-e8058039-374d-4fd5-bca5-69b73fb74d26.png)

I also notice that when clicking on a page, the url is `/file2.md` whereas it should be `/fr/file2` : back in the default language instead of staying in the `fr` part.

Thank you in advance ! 😄

**Comment by lukasgeiter** [comment]
Yeah I can absolutely reproduce this problem and I also understand what's happening.

When configuring the navigation in `mkdocs.yml`, the i18n plugin patches the entries to reflect the language it's currently processing. For example when building the French version, it will turn `index.md` into `index.fr.md`.

`.pages` files are not patched this way, so it's trying to find `index.md` which doesn't exist in the French version. As a fallback, awesome-pages treats `Welcome: index.md` as a relative link to `index.md`, resulting in the behavior you're seeing.

Unfortunately, I'm not sure how a good solution would look like. Maybe @ultrabug has an idea?

**Comment by ultrabug** [comment]
Well @lukasgeiter is not wrong I guess tho i18n does not "turn" `index.md` to `index.fr.md`, it just uses as the source of the index file because that's how mkdocs build process works.

@Argald0 you should go fully with the `.pages` approach and use `strict: false` option of awesome-pages.

That's how I do it on my own website so you have a [working example there](https://github.com/ultrabug/ultrabug.fr).

Which means in your case that you should not use titles in your `.pages` nav, just use:

```yaml
nav:
    - index.md
    - index.fr.md
    - file2.md
    - file2.fr.md
```

and 

```
plugins:
    - search
    - awesome-pages:
        strict: false
```
