### ISSUE TITLE
Regex for excluding files

### ISSUE THREAD

**Issue by lin-ycv** [lukasgeiter/mkdocs-awesome-pages-plugin#63]
I'm trying to exclude all pages that starts with 'h' from showing in the nav, but i'm not successful in my attempts

my docs dir structure looks like this
```
docs/
├─.pages
├─index.md
├─Folder1/
| └─(bunch of image files)
└─Folder2/
  ├─File1.md
  └─Folder2.1/
    ├─File1.md
    ├─File2.md
    └─h_File3.md
 ```
in `.pages` i configured it according to https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/34#issuecomment-788704657
```
nav:
    - ... | regex=^(?!h).*$
```
which didn't work.

I tried to change it so that only files starting with lowercase alphabets will show (just for testing)
```
nav:
    - ... | regex=[a-z]+.md
```
but this gave me `none` for the nav bar instead  
All my file and folder names start with capitals, expect index and the file I want to exclude

I also tried to use the code in the comment as is
```
nav:
    - ... | regex=[^(?!template)].*$
```
and renamed `h_File3.md` to `template.md`, but the file still shows up on the nav

---

I'm using Material for MkDocs on GH pages, here's my settings:
<details>
  <summary>mkdocs.yml</summary>

```
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Noto Sans
    code: Source Code Pro
  favicon: assets/images/favicon.png
  icon:
    logo: icon/signature
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
  - tables
  - meta
plugins:
  - search
  - awesome-pages
extra:
  generator: false
extra_css:
  - assets/css/util.css
```

</details>
<details>
<summary>deploy action</summary>

```
name: action
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force
```

</details>

The contents of the file I want to exclude looks like this (if it matters)
```
---
title: h
description: Some description
tags: ['tag1, 'tag2']
---


# ![](../../assets/images/icon.png) Header

content for the file....
```

Anyone has any ideas on what I'm doing wrong?
