### ISSUE TITLE
Allow `mkdocs-gen-files` generated content

### ISSUE THREAD

**Issue by thejcannon** [lukasgeiter/mkdocs-awesome-pages-plugin#78]
:wave: Loving the plugin! 

Currently also loving https://github.com/oprypin/mkdocs-gen-files, but noticed that if I generate navs, or pages referenced by my static navs, they don't end up making it to the generated docsite.

E.g.
`mkdocs.yml`
```yaml
plugins:
  - gen-files:
      scripts:
        - generate_reference_docs.py
  - awesome-pages:
      filename: .nav.yaml
```

`generate_reference_docs.py`
```python
with mkdocs_gen_files.open(f"reference/global-options.md", "w") as f:
    f.write("Hello world!\n")
with mkdocs_gen_files.open(f"reference/goals/index.md", "w") as f:
    f.write("# Goals!\n")
with mkdocs_gen_files.open(f"reference/goals/.nav.yaml", "w") as f:
    f.write("nav:\n  - index.md\n")
```

along with:

```console
$ tree -a docs/markdown/reference
docs/markdown/reference
└── .nav.yaml
$ cat docs/markdown/reference/.nav.yaml 
nav:
  - Global Options: global-options.md
  - Goals: goals
```

Results in `Reference` being in the nav, but is "flat". No expand arrow.

Additionally, the pages _do_ exist, `/reference/global-options` is a valid URL and gives what I expect.
