### ISSUE TITLE
Deep `.pages.` files not respected

### ISSUE THREAD

**Issue by vermiculus** [lukasgeiter/mkdocs-awesome-pages-plugin#89]
I'm hoping I'm just doing something wrong, but it appears that a deep `.pages` file is not found/respected.

In the site generated from https://github.com/vermiculus/awesome-pages-bug, it looks like title overrides aren't being respected. Even adding a new fake entry in the nav doesn't appear to be picked up.

The below screenshot is in contradiction with the `.pages` definition [here](https://github.com/vermiculus/awesome-pages-bug/blob/main/docs/guide/my-dir/.pages):

```yaml
# -*- yaml -*-
nav:
  - Landing: index.md
  - Page E: page-e.md
  - Page F: page-f.md
```

<img width="514" alt="image" src="https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/assets/2082195/9aa9acdb-e052-4058-a2b5-276018f6781b">

This `.pages` file is located at `docs/guide/my-dir/.pages`. Other, less deep files seem to be respected.
